### ISSUE TITLE
The static native method getNativeLibraryVersion() throws a UnsatisfiedLinkError

### ISSUE THREAD

**Issue by bmhm** [java-native/java-simple-serial-connector#16]
Invoking the method `SerialNativeInterface.getNativeLibraryVersion()` will throw an `UnsatisfiedLinkError`.

I do not why this is the case. The according `junit` test-case is deactivated due to the fact that this has not been resolved yet. Please see `SerialNativeInterfaceTest` (https://github.com/java-native/java-simple-serial-connector/blob/c77563e3e08fadddd1d950986a3036240b20c92f/src/test/java/jssc/SerialNativeInterfaceTest.java#L32) for further information.

This method is expected to work.

**Comment by tresf** [comment]
@bmhm fixed this in https://github.com/java-native/java-simple-serial-connector/pull/15/commits/90fb0a3538b00dd8429d4f2dfdd9da9e6924b06c, which was squashed into f4170b0 closed with merge of #15.
