### ISSUE TITLE
Use the maven ${project.version} for the native library

### ISSUE THREAD

**Issue by bmhm** [java-native/java-simple-serial-connector#17]
The native  `cpp` sources should use the version from the maven `pom.xml`.

## Implementation details
* Maven can export the project version to the `cmake` process.
  This must be configured in `pom.xml`. See the existing `<argLine>` entries in the maven antrun task.
* This needs to be done for both the Unix and the Windows versions of the `.cpp` file.

Question: Can cmake substitute and/or use the argument and insert it into the specific `cpp` file at compile time?

https://github.com/java-native/java-simple-serial-connector/blob/c77563e3e08fadddd1d950986a3036240b20c92f/src/main/cpp/_nix_based/jssc.cpp#L55

For a trained `cmake` user, this is probably not a very complex task.

**Comment by tresf** [comment]
> Can cmake substitute and/or use the argument and insert it into the specific cpp file at compile time?

Yes, it's called `#cmakedefine`, explained here: https://cmake.org/cmake/help/v3.2/command/configure_file.html#example.

It does require a dedicated header file, so we'll need to add one that can be configured and included (or alternately reconfigure the one that `javah` spits out).

**Comment by tresf** [comment]
Closed via f4170b0
